/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as HealthCheckRouteImport } from './app/health-check'
import { Route as OwnerIndexRouteImport } from './app/owner/index'
import { Route as OwnerDashboardRouteImport } from './app/owner/dashboard'

const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/health-check': typeof HealthCheckRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/health-check': typeof HealthCheckRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/health-check': typeof HealthCheckRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/health-check' | '/owner/dashboard' | '/owner'
  fileRoutesByTo: FileRoutesByTo
  to: '/health-check' | '/owner/dashboard' | '/owner'
  id: '__root__' | '/health-check' | '/owner/dashboard' | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HealthCheckRoute: typeof HealthCheckRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HealthCheckRoute: HealthCheckRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
