import { DemoBankAccount, DemoTransaction, DemoOffering, DemoInvestment, DemoDrawRequest, DemoInvoice, DemoProject } from './types'

// Bank Accounts - Enhanced with more realistic options
export const mockBankAccounts: DemoBankAccount[] = [
  {
    id: 'bank-1',
    bankName: 'Chase Bank',
    accountType: 'CHECKING',
    last4: '4242',
    status: 'VERIFIED',
    isDefault: true,
  },
  {
    id: 'bank-2',
    bankName: 'Bank of America',
    accountType: 'SAVINGS',
    last4: '8765',
    status: 'VERIFIED',
    isDefault: false,
  },
  {
    id: 'bank-3',
    bankName: 'Wells Fargo',
    accountType: 'CHECKING',
    last4: '3456',
    status: 'VERIFIED',
    isDefault: false,
  },
]

// Transactions - Enhanced with comprehensive transaction history
export const mockTransactions: DemoTransaction[] = [
  // Recent Transactions
  {
    id: 'txn-1',
    type: 'DEPOSIT',
    amount: 250000,
    status: 'COMPLETED',
    date: new Date('2026-01-20'),
    description: 'Initial Investment - Sunset Apartments Phase 2',
    paymentMethod: 'ACH',
    from: 'Chase Bank ••4242',
    to: 'Escrow Account',
  },
  {
    id: 'txn-2',
    type: 'DISTRIBUTION',
    amount: 15750,
    status: 'COMPLETED',
    date: new Date('2026-01-15'),
    description: 'Q4 2025 Distribution - Downtown Office Tower (6.3% return)',
    paymentMethod: 'ACH',
    from: 'Escrow Account',
    to: 'Chase Bank ••4242',
  },
  {
    id: 'txn-3',
    type: 'DEPOSIT',
    amount: 150000,
    status: 'PROCESSING',
    date: new Date('2026-01-22'),
    description: 'Additional Investment - Marina Bay Apartments',
    paymentMethod: 'WIRE',
    from: 'Bank of America ••8765',
    to: 'Escrow Account',
  },
  {
    id: 'txn-4',
    type: 'DISTRIBUTION',
    amount: 8750,
    status: 'COMPLETED',
    date: new Date('2026-01-10'),
    description: 'Monthly Distribution - Sunset Apartments (3.5% return)',
    paymentMethod: 'ACH',
    from: 'Escrow Account',
    to: 'Chase Bank ••4242',
  },
  {
    id: 'txn-5',
    type: 'PLATFORM_FEE',
    amount: -500,
    status: 'COMPLETED',
    date: new Date('2026-01-20'),
    description: 'Platform Management Fee - 0.2% Annual',
    paymentMethod: 'ACH',
    from: 'Chase Bank ••4242',
    to: 'RealCo Platform',
  },
  // Historical Transactions
  {
    id: 'txn-6',
    type: 'DISTRIBUTION',
    amount: 12250,
    status: 'COMPLETED',
    date: new Date('2025-12-15'),
    description: 'Q3 2025 Distribution - Marina Bay Apartments (4.9% return)',
    paymentMethod: 'ACH',
    from: 'Escrow Account',
    to: 'Chase Bank ••4242',
  },
  {
    id: 'txn-7',
    type: 'DEPOSIT',
    amount: 100000,
    status: 'COMPLETED',
    date: new Date('2025-11-05'),
    description: 'Investment in Tech Park Office Complex',
    paymentMethod: 'ACH',
    from: 'Wells Fargo ••3456',
    to: 'Escrow Account',
  },
  {
    id: 'txn-8',
    type: 'DISTRIBUTION',
    amount: 18900,
    status: 'COMPLETED',
    date: new Date('2025-10-20'),
    description: 'Special Distribution - Downtown Office Refinancing (7.6% return)',
    paymentMethod: 'WIRE',
    from: 'Escrow Account',
    to: 'Bank of America ••8765',
  },
  {
    id: 'txn-9',
    type: 'DEPOSIT',
    amount: 200000,
    status: 'COMPLETED',
    date: new Date('2025-09-12'),
    description: 'Initial Investment - Marina Bay Apartments',
    paymentMethod: 'ACH',
    from: 'Chase Bank ••4242',
    to: 'Escrow Account',
  },
  {
    id: 'txn-10',
    type: 'DISTRIBUTION',
    amount: 9800,
    status: 'COMPLETED',
    date: new Date('2025-09-01'),
    description: 'Q2 2025 Distribution - Sunset Apartments (3.9% return)',
    paymentMethod: 'ACH',
    from: 'Escrow Account',
    to: 'Chase Bank ••4242',
  },
  {
    id: 'txn-11',
    type: 'PLATFORM_FEE',
    amount: -350,
    status: 'COMPLETED',
    date: new Date('2025-09-12'),
    description: 'Platform Management Fee - 0.2% Annual',
    paymentMethod: 'ACH',
    from: 'Chase Bank ••4242',
    to: 'RealCo Platform',
  },
  {
    id: 'txn-12',
    type: 'DEPOSIT',
    amount: 75000,
    status: 'COMPLETED',
    date: new Date('2025-08-20'),
    description: 'Additional Investment - Sunset Apartments Expansion',
    paymentMethod: 'ACH',
    from: 'Bank of America ••8765',
    to: 'Escrow Account',
  },
  {
    id: 'txn-13',
    type: 'DISTRIBUTION',
    amount: 11200,
    status: 'COMPLETED',
    date: new Date('2025-07-15'),
    description: 'Q1 2025 Distribution - Marina Bay Apartments (5.6% return)',
    paymentMethod: 'ACH',
    from: 'Escrow Account',
    to: 'Chase Bank ••4242',
  },
  {
    id: 'txn-14',
    type: 'DEPOSIT',
    amount: 300000,
    status: 'COMPLETED',
    date: new Date('2025-06-15'),
    description: 'Initial Investment - Sunset Apartments',
    paymentMethod: 'WIRE',
    from: 'Chase Bank ••4242',
    to: 'Escrow Account',
  },
  {
    id: 'txn-15',
    type: 'DISTRIBUTION',
    amount: 14500,
    status: 'COMPLETED',
    date: new Date('2025-06-01'),
    description: 'Q4 2024 Distribution - Downtown Office Tower (5.8% return)',
    paymentMethod: 'ACH',
    from: 'Escrow Account',
    to: 'Chase Bank ••4242',
  },
]

// Offerings - Enhanced with detailed property information
export const mockOfferings: DemoOffering[] = [
  {
    id: 'offer-1',
    name: 'Marina Bay Luxury Apartments',
    location: 'San Diego, CA',
    minInvestment: 50000,
    targetRaise: 12000000,
    currentRaised: 9250000,
    status: 'ACTIVE',
    targetReturn: '15-20% IRR',
    holdPeriod: '3-5 years',
    assetType: 'Multifamily',
    units: 84,
    occupancyRate: '95%',
    description: 'Luxury waterfront apartment complex with premium amenities including rooftop pool, fitness center, and concierge service. Located in prime San Diego harbor district.',
  },
  {
    id: 'offer-2',
    name: 'Tech Park Office Complex',
    location: 'Seattle, WA',
    minInvestment: 100000,
    targetRaise: 25000000,
    currentRaised: 17800000,
    status: 'ACTIVE',
    targetReturn: '18-23% IRR',
    holdPeriod: '5-7 years',
    assetType: 'Commercial Office',
    squareFeet: 145000,
    occupancyRate: '88%',
    description: 'Class A office space in the heart of Seattle tech corridor. Major tenants include Fortune 500 technology companies. Recent renovation with LEED Gold certification.',
  },
  {
    id: 'offer-3',
    name: 'Sunset Garden Apartments',
    location: 'Austin, TX',
    minInvestment: 25000,
    targetRaise: 8000000,
    currentRaised: 8000000,
    status: 'FUNDED',
    targetReturn: '16-21% IRR',
    holdPeriod: '4-6 years',
    assetType: 'Multifamily',
    units: 120,
    occupancyRate: '97%',
    description: 'Modern garden-style apartment community in rapidly growing East Austin. Pet-friendly with resort-style amenities and walkable to downtown.',
  },
  {
    id: 'offer-4',
    name: 'Riverside Mixed-Use Development',
    location: 'Portland, OR',
    minInvestment: 75000,
    targetRaise: 18500000,
    currentRaised: 12100000,
    status: 'ACTIVE',
    targetReturn: '17-22% IRR',
    holdPeriod: '4-6 years',
    assetType: 'Mixed-Use',
    units: 96,
    squareFeet: 28000,
    occupancyRate: '91%',
    description: 'Premier mixed-use development featuring residential lofts and ground-floor retail. Situated along the Willamette River with stunning views and bike-friendly infrastructure.',
  },
  {
    id: 'offer-5',
    name: 'Desert Oasis Retail Center',
    location: 'Phoenix, AZ',
    minInvestment: 50000,
    targetRaise: 9500000,
    currentRaised: 5800000,
    status: 'ACTIVE',
    targetReturn: '14-18% IRR',
    holdPeriod: '5-7 years',
    assetType: 'Retail',
    squareFeet: 65000,
    occupancyRate: '93%',
    description: 'Well-positioned neighborhood retail center anchored by national grocery chain. High-traffic location in affluent Phoenix suburb with strong demographics.',
  },
  {
    id: 'offer-6',
    name: 'Mountain View Senior Living',
    location: 'Denver, CO',
    minInvestment: 100000,
    targetRaise: 22000000,
    currentRaised: 22000000,
    status: 'FUNDED',
    targetReturn: '15-19% IRR',
    holdPeriod: '7-10 years',
    assetType: 'Senior Housing',
    units: 156,
    occupancyRate: '98%',
    description: 'Premium assisted living and memory care facility. State-of-the-art amenities, 24/7 medical staff, and stunning Rocky Mountain views. High-demand market with aging demographics.',
  },
]

// Investments - Enhanced with detailed performance tracking
export const mockInvestments: DemoInvestment[] = [
  {
    id: 'inv-1',
    offeringId: 'offer-3',
    amount: 250000,
    date: new Date('2025-06-15'),
    status: 'ACTIVE',
    returnToDate: 21875, // 8.75% over 7 months
    currentValue: 271875,
    distributionsReceived: 3,
    lastDistributionDate: new Date('2026-01-10'),
    annualizedReturn: 15.2,
  },
  {
    id: 'inv-2',
    offeringId: 'offer-1',
    amount: 150000,
    date: new Date('2025-09-12'),
    status: 'ACTIVE',
    returnToDate: 8250, // 5.5% over 4 months
    currentValue: 158250,
    distributionsReceived: 2,
    lastDistributionDate: new Date('2026-01-15'),
    annualizedReturn: 16.5,
  },
  {
    id: 'inv-3',
    offeringId: 'offer-2',
    amount: 100000,
    date: new Date('2025-11-05'),
    status: 'ACTIVE',
    returnToDate: 3800, // 3.8% over 2.5 months
    currentValue: 103800,
    distributionsReceived: 1,
    lastDistributionDate: new Date('2025-12-15'),
    annualizedReturn: 18.2,
  },
  {
    id: 'inv-4',
    offeringId: 'offer-6',
    amount: 200000,
    date: new Date('2024-08-20'),
    status: 'ACTIVE',
    returnToDate: 42500, // 21.25% over 17 months
    currentValue: 242500,
    distributionsReceived: 6,
    lastDistributionDate: new Date('2026-01-01'),
    annualizedReturn: 15.0,
  },
]

// Draw Requests - Enhanced with comprehensive construction tracking
export const mockDrawRequests: DemoDrawRequest[] = [
  // Recent Draw Requests
  {
    id: 'DR-2026-007',
    projectName: 'Sunset Garden Apartments',
    amount: 485000,
    category: 'Framing',
    status: 'APPROVED',
    date: new Date('2026-01-20'),
    description: 'Framing completion for Buildings A & B - All 120 units. Includes lumber, structural steel, and labor. Passed city inspection on 1/18.',
    inspectionDate: new Date('2026-01-18'),
    inspector: 'City of Austin Building Dept',
  },
  {
    id: 'DR-2026-006',
    projectName: 'Marina Bay Luxury Apartments',
    amount: 625000,
    category: 'MEP',
    status: 'UNDER_REVIEW',
    date: new Date('2026-01-18'),
    description: 'Mechanical, Electrical, and Plumbing rough-in for Floors 1-4. Includes HVAC systems, electrical panels, plumbing fixtures, and fire suppression.',
    requestedBy: 'Johnson Construction Co',
  },
  {
    id: 'DR-2026-005',
    projectName: 'Sunset Garden Apartments',
    amount: 450000,
    category: 'Foundation',
    status: 'PAID',
    date: new Date('2026-01-15'),
    description: 'Foundation work completed for Buildings A and B. Includes concrete, rebar, waterproofing, and drainage systems. Total 32,000 sq ft foundation.',
    paidDate: new Date('2026-01-17'),
    checkNumber: 'CHK-98765',
  },
  {
    id: 'DR-2026-004',
    projectName: 'Tech Park Office Complex',
    amount: 895000,
    category: 'Facade',
    status: 'PAID',
    date: new Date('2026-01-12'),
    description: 'Curtain wall and exterior facade installation - North and East elevations. Includes high-performance glass, aluminum framing, and weatherproofing.',
    paidDate: new Date('2026-01-14'),
    checkNumber: 'CHK-98764',
  },
  {
    id: 'DR-2026-003',
    projectName: 'Sunset Garden Apartments',
    amount: 325000,
    category: 'Site Work',
    status: 'PAID',
    date: new Date('2026-01-08'),
    description: 'Site preparation, grading, and utility connections. Includes storm water management, sanitary sewer, water mains, and landscaping base.',
    paidDate: new Date('2026-01-10'),
    checkNumber: 'CHK-98763',
  },
  {
    id: 'DR-2026-002',
    projectName: 'Marina Bay Luxury Apartments',
    amount: 550000,
    category: 'Structural',
    status: 'PAID',
    date: new Date('2026-01-05'),
    description: 'Structural steel and concrete work for podium level. Includes post-tensioned slabs, columns, and seismic reinforcement.',
    paidDate: new Date('2026-01-07'),
    checkNumber: 'CHK-98762',
  },
  {
    id: 'DR-2026-001',
    projectName: 'Sunset Garden Apartments',
    amount: 180000,
    category: 'Soft Costs',
    status: 'PAID',
    date: new Date('2026-01-01'),
    description: 'Architecture, engineering, and permitting fees for project Phase 2. Includes structural engineering, MEP design, and city permit fees.',
    paidDate: new Date('2026-01-03'),
    checkNumber: 'CHK-98761',
  },
  // Historical Draw Requests
  {
    id: 'DR-2025-012',
    projectName: 'Tech Park Office Complex',
    amount: 1250000,
    category: 'Interior Finishes',
    status: 'PAID',
    date: new Date('2025-12-20'),
    description: 'Interior finishes for Floors 6-10. Includes drywall, painting, flooring (carpet and hardwood), and ceiling systems.',
    paidDate: new Date('2025-12-22'),
    checkNumber: 'CHK-98760',
  },
  {
    id: 'DR-2025-011',
    projectName: 'Marina Bay Luxury Apartments',
    amount: 420000,
    category: 'Site Work',
    status: 'PAID',
    date: new Date('2025-12-10'),
    description: 'Site demolition, excavation, and shoring. Includes removal of existing structures, soil remediation, and temporary support systems.',
    paidDate: new Date('2025-12-12'),
    checkNumber: 'CHK-98759',
  },
  {
    id: 'DR-2025-010',
    projectName: 'Sunset Garden Apartments',
    amount: 280000,
    category: 'Soft Costs',
    status: 'PAID',
    date: new Date('2025-11-28'),
    description: 'Legal, insurance, and financing costs. Includes title insurance, construction insurance, lender fees, and legal review.',
    paidDate: new Date('2025-11-30'),
    checkNumber: 'CHK-98758',
  },
]

// Invoices - Enhanced with detailed contractor billing
export const mockInvoices: DemoInvoice[] = [
  {
    id: 'inv-2026-008',
    invoiceNumber: 'INV-2026-008',
    projectName: 'Sunset Garden Apartments',
    amount: 52500,
    status: 'SUBMITTED',
    date: new Date('2026-01-23'),
    description: 'Electrical rough-in for Building B - 60 units. Includes panel installation, conduit runs, and fixture boxes.',
    vendorName: 'Premier Electric Solutions',
    vendorContact: 'Mike Johnson - (512) 555-0123',
    dueDate: new Date('2026-02-22'),
  },
  {
    id: 'inv-2026-007',
    invoiceNumber: 'INV-2026-007',
    projectName: 'Marina Bay Luxury Apartments',
    amount: 68900,
    status: 'APPROVED',
    date: new Date('2026-01-21'),
    description: 'Curtain wall installation - South facade Phase 1. High-performance glass and aluminum framing.',
    vendorName: 'Coastal Glass & Glazing',
    vendorContact: 'Sarah Chen - (619) 555-0187',
    approvedDate: new Date('2026-01-22'),
    dueDate: new Date('2026-02-20'),
  },
  {
    id: 'inv-2026-006',
    invoiceNumber: 'INV-2026-006',
    projectName: 'Sunset Garden Apartments',
    amount: 45800,
    status: 'APPROVED',
    date: new Date('2026-01-20'),
    description: 'Electrical rough-in for Building A - 60 units completed. Panel upgrades and EV charging prep included.',
    vendorName: 'Premier Electric Solutions',
    vendorContact: 'Mike Johnson - (512) 555-0123',
    approvedDate: new Date('2026-01-21'),
    dueDate: new Date('2026-02-19'),
  },
  {
    id: 'inv-2026-005',
    invoiceNumber: 'INV-2026-005',
    projectName: 'Tech Park Office Complex',
    amount: 94250,
    status: 'UNDER_REVIEW',
    date: new Date('2026-01-18'),
    description: 'HVAC systems installation - Floors 8-10. Variable refrigerant flow systems with advanced controls.',
    vendorName: 'Northwest Climate Control',
    vendorContact: 'David Park - (206) 555-0195',
    dueDate: new Date('2026-02-17'),
  },
  {
    id: 'inv-2026-004',
    invoiceNumber: 'INV-2026-004',
    projectName: 'Marina Bay Luxury Apartments',
    amount: 38650,
    status: 'PAID',
    date: new Date('2026-01-16'),
    description: 'Plumbing rough-in for podium level - Common areas and retail spaces.',
    vendorName: 'Pacific Plumbing Contractors',
    vendorContact: 'Robert Martinez - (619) 555-0142',
    paidDate: new Date('2026-01-18'),
    paymentMethod: 'ACH',
    checkNumber: 'ACH-45123',
    dueDate: new Date('2026-02-15'),
  },
  {
    id: 'inv-2026-003',
    invoiceNumber: 'INV-2026-003',
    projectName: 'Tech Park Office Complex',
    amount: 125400,
    status: 'PAID',
    date: new Date('2026-01-15'),
    description: 'Flooring installation - Floors 6-7. Premium carpet tiles in offices, porcelain tile in common areas.',
    vendorName: 'Elite Flooring Solutions',
    vendorContact: 'Jennifer Wong - (206) 555-0156',
    paidDate: new Date('2026-01-17'),
    paymentMethod: 'CHECK',
    checkNumber: 'CHK-45122',
    dueDate: new Date('2026-02-14'),
  },
  {
    id: 'inv-2026-002',
    invoiceNumber: 'INV-2026-002',
    projectName: 'Sunset Garden Apartments',
    amount: 76300,
    status: 'PAID',
    date: new Date('2026-01-12'),
    description: 'Framing materials delivery - Buildings A & B. Premium lumber package including engineered joists.',
    vendorName: 'Austin Lumber Supply',
    vendorContact: 'Tom Harrison - (512) 555-0198',
    paidDate: new Date('2026-01-14'),
    paymentMethod: 'ACH',
    checkNumber: 'ACH-45121',
    dueDate: new Date('2026-02-11'),
  },
  {
    id: 'inv-2026-001',
    invoiceNumber: 'INV-2026-001',
    projectName: 'Marina Bay Luxury Apartments',
    amount: 185000,
    status: 'PAID',
    date: new Date('2026-01-08'),
    description: 'Structural steel fabrication and installation - Podium level. Includes seismic bracing and connections.',
    vendorName: 'Coastal Steel Fabricators',
    vendorContact: 'James Rodriguez - (619) 555-0171',
    paidDate: new Date('2026-01-10'),
    paymentMethod: 'WIRE',
    checkNumber: 'WIRE-45120',
    dueDate: new Date('2026-02-07'),
  },
]

// Projects - Enhanced with comprehensive construction details
export const mockProjects: DemoProject[] = [
  {
    id: 'proj-1',
    name: 'Sunset Garden Apartments',
    totalBudget: 12000000,
    drawnToDate: 4785000,
    status: 'IN_PROGRESS',
    startDate: new Date('2025-12-01'),
    expectedCompletion: new Date('2027-06-30'),
    completionPercentage: 42,
    address: '1234 Riverside Drive, Austin, TX 78704',
    developer: 'Texas Development Partners',
    generalContractor: 'Summit Construction Group',
    architect: 'Modern Design Associates',
    units: 120,
    totalSquareFeet: 96000,
    budgetCategories: [
      { name: 'Site Work', budgeted: 850000, spent: 825000, percentage: 97 },
      { name: 'Foundation', budgeted: 1200000, spent: 1180000, percentage: 98 },
      { name: 'Framing', budgeted: 2100000, spent: 1950000, percentage: 93 },
      { name: 'MEP', budgeted: 2400000, spent: 680000, percentage: 28 },
      { name: 'Interior Finishes', budgeted: 1800000, spent: 0, percentage: 0 },
      { name: 'Exterior', budgeted: 1400000, spent: 0, percentage: 0 },
      { name: 'Soft Costs', budgeted: 1250000, spent: 150000, percentage: 12 },
      { name: 'Contingency', budgeted: 1000000, spent: 0, percentage: 0 },
    ],
    milestones: [
      { name: 'Site Prep Complete', targetDate: new Date('2026-01-15'), actualDate: new Date('2026-01-12'), status: 'COMPLETED' },
      { name: 'Foundation Complete', targetDate: new Date('2026-02-28'), actualDate: new Date('2026-02-25'), status: 'COMPLETED' },
      { name: 'Framing Complete', targetDate: new Date('2026-05-15'), actualDate: null, status: 'IN_PROGRESS' },
      { name: 'MEP Rough-in Complete', targetDate: new Date('2026-08-30'), actualDate: null, status: 'NOT_STARTED' },
      { name: 'Final Inspections', targetDate: new Date('2027-05-30'), actualDate: null, status: 'NOT_STARTED' },
      { name: 'Certificate of Occupancy', targetDate: new Date('2027-06-30'), actualDate: null, status: 'NOT_STARTED' },
    ],
  },
  {
    id: 'proj-2',
    name: 'Marina Bay Luxury Apartments',
    totalBudget: 24500000,
    drawnToDate: 8950000,
    status: 'IN_PROGRESS',
    startDate: new Date('2025-09-15'),
    expectedCompletion: new Date('2027-12-31'),
    completionPercentage: 38,
    address: '789 Harbor View Boulevard, San Diego, CA 92101',
    developer: 'Pacific Coast Developments',
    generalContractor: 'Oceanside Builders Inc',
    architect: 'Coastal Design Studio',
    units: 84,
    totalSquareFeet: 112000,
    budgetCategories: [
      { name: 'Site Work', budgeted: 1850000, spent: 1820000, percentage: 98 },
      { name: 'Foundation', budgeted: 2100000, spent: 2050000, percentage: 98 },
      { name: 'Structural', budgeted: 4200000, spent: 2850000, percentage: 68 },
      { name: 'MEP', budgeted: 3800000, spent: 1240000, percentage: 33 },
      { name: 'Facade', budgeted: 3500000, spent: 895000, percentage: 26 },
      { name: 'Interior Finishes', budgeted: 4200000, spent: 0, percentage: 0 },
      { name: 'Amenities', budgeted: 2400000, spent: 0, percentage: 0 },
      { name: 'Soft Costs', budgeted: 1450000, spent: 145000, percentage: 10 },
      { name: 'Contingency', budgeted: 1000000, spent: 0, percentage: 0 },
    ],
    milestones: [
      { name: 'Demolition & Site Prep', targetDate: new Date('2025-11-30'), actualDate: new Date('2025-11-28'), status: 'COMPLETED' },
      { name: 'Foundation & Podium', targetDate: new Date('2026-02-15'), actualDate: new Date('2026-02-10'), status: 'COMPLETED' },
      { name: 'Structural Steel Complete', targetDate: new Date('2026-06-30'), actualDate: null, status: 'IN_PROGRESS' },
      { name: 'Facade Installation', targetDate: new Date('2026-10-31'), actualDate: null, status: 'IN_PROGRESS' },
      { name: 'Interior Build-out', targetDate: new Date('2027-06-30'), actualDate: null, status: 'NOT_STARTED' },
      { name: 'Grand Opening', targetDate: new Date('2027-12-31'), actualDate: null, status: 'NOT_STARTED' },
    ],
  },
  {
    id: 'proj-3',
    name: 'Tech Park Office Complex',
    totalBudget: 42000000,
    drawnToDate: 38250000,
    status: 'IN_PROGRESS',
    startDate: new Date('2024-03-01'),
    expectedCompletion: new Date('2026-08-31'),
    completionPercentage: 89,
    address: '2500 Innovation Way, Seattle, WA 98109',
    developer: 'Northwest Commercial Properties',
    generalContractor: 'Cascade Construction LLC',
    architect: 'Tech Space Architects',
    totalSquareFeet: 145000,
    budgetCategories: [
      { name: 'Site Work', budgeted: 2800000, spent: 2750000, percentage: 98 },
      { name: 'Foundation', budgeted: 3500000, spent: 3480000, percentage: 99 },
      { name: 'Structural', budgeted: 8500000, spent: 8420000, percentage: 99 },
      { name: 'MEP', budgeted: 9200000, spent: 8950000, percentage: 97 },
      { name: 'Facade', budgeted: 6800000, spent: 6750000, percentage: 99 },
      { name: 'Interior Finishes', budgeted: 7200000, spent: 6100000, percentage: 85 },
      { name: 'Technology', budgeted: 1800000, spent: 1200000, percentage: 67 },
      { name: 'Soft Costs', budgeted: 1700000, spent: 550000, percentage: 32 },
      { name: 'Contingency', budgeted: 500000, spent: 50000, percentage: 10 },
    ],
    milestones: [
      { name: 'Site Mobilization', targetDate: new Date('2024-04-01'), actualDate: new Date('2024-03-28'), status: 'COMPLETED' },
      { name: 'Foundation Complete', targetDate: new Date('2024-08-31'), actualDate: new Date('2024-08-25'), status: 'COMPLETED' },
      { name: 'Structural Topping Out', targetDate: new Date('2025-03-31'), actualDate: new Date('2025-03-20'), status: 'COMPLETED' },
      { name: 'Facade Complete', targetDate: new Date('2025-10-31'), actualDate: new Date('2025-10-28'), status: 'COMPLETED' },
      { name: 'MEP Systems Operational', targetDate: new Date('2026-04-30'), actualDate: new Date('2026-04-22'), status: 'COMPLETED' },
      { name: 'Tenant Improvement Completion', targetDate: new Date('2026-07-31'), actualDate: null, status: 'IN_PROGRESS' },
      { name: 'Final Certificate of Occupancy', targetDate: new Date('2026-08-31'), actualDate: null, status: 'NOT_STARTED' },
    ],
  },
  {
    id: 'proj-4',
    name: 'Riverside Mixed-Use Development',
    totalBudget: 19800000,
    drawnToDate: 5940000,
    status: 'IN_PROGRESS',
    startDate: new Date('2025-10-01'),
    expectedCompletion: new Date('2027-10-31'),
    completionPercentage: 31,
    address: '456 Waterfront Plaza, Portland, OR 97204',
    developer: 'Columbia River Developments',
    generalContractor: 'Rose City Builders',
    architect: 'Urban Design Collective',
    units: 96,
    totalSquareFeet: 124000,
    budgetCategories: [
      { name: 'Site Work', budgeted: 1200000, spent: 1180000, percentage: 98 },
      { name: 'Foundation', budgeted: 1850000, spent: 1820000, percentage: 98 },
      { name: 'Structural', budgeted: 4200000, spent: 2520000, percentage: 60 },
      { name: 'MEP', budgeted: 3200000, spent: 420000, percentage: 13 },
      { name: 'Facade', budgeted: 2800000, spent: 0, percentage: 0 },
      { name: 'Residential Finishes', budgeted: 2950000, spent: 0, percentage: 0 },
      { name: 'Retail Build-out', budgeted: 1600000, spent: 0, percentage: 0 },
      { name: 'Soft Costs', budgeted: 1200000, spent: 0, percentage: 0 },
      { name: 'Contingency', budgeted: 800000, spent: 0, percentage: 0 },
    ],
    milestones: [
      { name: 'Site Prep & Demolition', targetDate: new Date('2025-11-30'), actualDate: new Date('2025-11-25'), status: 'COMPLETED' },
      { name: 'Foundation Complete', targetDate: new Date('2026-02-28'), actualDate: new Date('2026-02-20'), status: 'COMPLETED' },
      { name: 'Structural Frame Complete', targetDate: new Date('2026-07-31'), actualDate: null, status: 'IN_PROGRESS' },
      { name: 'MEP Rough-in', targetDate: new Date('2026-11-30'), actualDate: null, status: 'NOT_STARTED' },
      { name: 'Retail Spaces Ready', targetDate: new Date('2027-07-31'), actualDate: null, status: 'NOT_STARTED' },
      { name: 'Residential Units Complete', targetDate: new Date('2027-10-31'), actualDate: null, status: 'NOT_STARTED' },
    ],
  },
]

// Helper to get data by role
export const getMockDataForRole = (role: 'investor' | 'sponsor' | 'provider') => {
  switch (role) {
    case 'investor':
      return {
        offerings: mockOfferings.filter(o => o.status === 'ACTIVE'),
        investments: mockInvestments,
        transactions: mockTransactions.filter(t => 
          t.type === 'DEPOSIT' || t.type === 'DISTRIBUTION' || t.type === 'PLATFORM_FEE'
        ),
      }
    case 'sponsor':
      return {
        projects: mockProjects,
        drawRequests: mockDrawRequests,
        transactions: mockTransactions.filter(t => 
          t.type === 'CONSTRUCTION_DRAW' || t.type === 'DEPOSIT'
        ),
      }
    case 'provider':
      return {
        invoices: mockInvoices,
        transactions: mockTransactions.filter(t => 
          t.type === 'CONSTRUCTION_DRAW'
        ),
      }
    default:
      return {}
  }
}
